### ISSUE TITLE
CKE Editor sometimes returns the following error

### ISSUE THREAD

**Issue by Marnix-IxD** [mendix/CKEditorForMendix#3] opened 2015-02-09 07:57 UTC
ckeditorformendix - Unable to add contents to editor, no _editor object available

the editor doesn't load in this scenario is after opening it the second time.

**Comment by RoelandSalij** [comment] 2015-02-09 14:19
Did you encouter this issue in version 1.1?

**Comment by Marnix-IxD** [comment] 2015-02-09 15:42
Yes

**Comment by RoelandSalij** [comment] 2015-02-09 16:11
Thanks for your feedback! Can you please verify if the issue is fixed in v1.2?
I tested it with the test project in this repository and it seems like the issue does not occur anymore.

**Closed** 2015-03-31 14:28 UTC
