### ISSUE TITLE
The images won't show up on my mobile pages using the mendix developer app. It's only showing placeholders.

### ISSUE THREAD

**Issue by Wilfried-Mulder** [mendix/CKEditorForMendix#29] opened 2016-03-03 12:15 UTC

**Comment by JelteMX** [comment] 2016-03-03 13:19
Can you please elaborate on this issue? What is the Modeler version, how do you upload them, what are the settings in the widget? If you can provide some screenshots, that would be nice. It might have to do with the way we handle incoming images (I have seen something similar happening on Mobile)

**Comment by Wilfried-Mulder** [comment] 2016-03-03 13:31
Modeler version 5.21.1. Upload is using drag & drop from Windows explorer. The picture is properly shown in safari on my mobile device, but there's a placeholder when testing the mendix developer app, check the screenshts. Hope this helps. Tx
![img_6978](https://cloud.githubusercontent.com/assets/8004408/13495689/6ea863a2-e14c-11e5-99fa-c845a982e5b3.PNG)
![img_6979](https://cloud.githubusercontent.com/assets/8004408/13495690/6ea9a3d4-e14c-11e5-901a-1df47a24fd02.PNG)

**Comment by JelteMX** [comment] 2016-03-03 14:06
This seems to be an issue with the developer app then? If it works on mobile web, then there isn't an issue with the CKEditor. We'll see if we can reproduce this behaviour...

**Comment by Wilfried-Mulder** [comment] 2016-03-03 14:24
It's not the mendix developer app itself, because the issue also occurs on our own hybrid mobile app. We use the mendix developer app to see if we can quickly reproduce the error.

**Comment by JelteMX** [comment] 2016-03-03 14:36
Could you maybe send a test-project/email to community [at] mendix.com? (mention my name) I need to see if we can reproduce the problem...

**Comment by Wilfried-Mulder** [comment] 2016-03-03 14:50
The package is underway. You can test this by adding an image on the validation page, then click save. Next step is to open the homepage in the mendix developer app and check the results.

**Comment by JelteMX** [comment] 2016-03-03 15:27
Never mind, we have reproduced the issue here. But... the problem lies in the url that is added, which should be dynamic I guess. We'll if there is a fix, otherwise I have to report this to the team that maintains the developer app

**Comment by JelteMX** [comment] 2016-03-04 09:31
It seems to be that 

```html
<img src="file?guid=xxxxxx" />
```

Does not show an image in the hybrid app. Which is weird, because in the CKEditor test app (included in this repo) the images are shown when I click on "Images" (which will give me a list of all the images). So it's actually an issue with the url that is included I guess.

When I look in the client API, the image url should be build as:

```js
var url = mx.appUrl + "file?" + [
                "guid=" + guid,
                "changedDate=" + changedDate
            ].join("&");
```

And there it will pose a problem, because the url can change... So I might have to do some hacking in the [CKEditorViewer](https://github.com/mendix/CKEditorForMendix/blob/master/src/CKEditorForMendix/widget/CKEditorViewerForMendix.js) to dynamically change this url...

**Comment by JelteMX** [comment] 2016-03-04 11:28
@Wilfried-Mulder can you test [this version](https://github.com/mendix/CKEditorForMendix/raw/bugfix/hybrid/test/widgets/CKEditorForMendix.mpk) for me?

I created a potential bugfix in [bugfix/hybrid](https://github.com/mendix/CKEditorForMendix/tree/bugfix/hybrid)

**Comment by JelteMX** [comment] 2016-03-04 11:30
This will not solve the problem not showing in the editor (but this shouldnt be a problem on hybrid since you cannot upload images in a hybrid app right now), but it does fix the problem in the CKEditorViewerForMendix. Will test this possible fix today as well

**Comment by Wilfried-Mulder** [comment] 2016-03-04 11:57
Nice work @JelteMX This solves our issue. Tested on both the mendix developer app and our own hybrid app. Tx

**Comment by JelteMX** [comment] 2016-03-04 12:19
Great! Will merge this into the editor and update it in the AppStore asap

**Comment by JelteMX** [comment] 2016-03-04 14:09
Even better... In our last [commit](https://github.com/mendix/CKEditorForMendix/commit/406ee91a41090550c90da67e6e30d0370cde3faa) we even fixed the editor view. So images are now properly shown in the CKEditor on the hybrid app as well. Can you test this again for me? (redownload the version mentioned above)

**Comment by Wilfried-Mulder** [comment] 2016-03-07 10:57
It seems that this fix was not implemented on the simple image browser functionality that comes along the CKEditor. If you select an image from the simple browser window, then the console says file not found, and the image won't show up in your content. Can you confirm?

**Comment by JelteMX** [comment] 2016-03-07 14:57
I will recheck this. As far as I have seen, it should work

**Comment by Wilfried-Mulder** [comment] 2016-03-09 08:04
To reproduce this you need to create the content with a picture. Then create another content, and use the simple image browser to insert the same picture. Hope this helps.

**Comment by JelteMX** [comment] 2016-03-09 09:50
It might have to do with the fact that the content has a reference to the image. I'll do some checking today. Is this issue again only in the hybrid app? If it's a seperate one, I'll close this issue and create a new one.

**Comment by Wilfried-Mulder** [comment] 2016-03-09 10:05
The issue is related to the CKEditor on the desktop pages not hybrid specific. If you restore a previous version of the CKEditor without the hybrid fix, then this feature works fine.

**Comment by JelteMX** [comment] 2016-03-10 12:26
Problem found, fix is coming. I am closing this issue. I'll refer to #31

**Closed by JelteMX** 2016-03-10 12:26 UTC
